### PR TITLE
Added User-Agent header to httpFactory and Constants class to hold th…

### PR DESCRIPTION
**Pull request by mediumTaj**
Added a User-Agent header to the HttpFactory and a Constants class to hold the version number. Let me know if you have a better way to implement this.

### CODE REVIEW

**Comment by atilatosta** [comment]
@mediumTaj I think that we have separated packages, may exist differing numbers of versions. What do you think?

**Comment by mediumTaj** [comment]
Hmm yes, I touch on it [here](https://github.com/atilatosta/dotnet-standard-sdk/issues/47) and [here](https://github.com/atilatosta/dotnet-standard-sdk/issues/51). Will we version per service? or keep it simple and have one sdk version? 

It looks like [amazon](https://www.nuget.org/profiles/awsdotnet) versions per package. Let me check with @german. Maybe we send one version (base sdk) for user-agent but keep separate versions for services?

**Comment by mediumTaj** [comment]
@atilatosta ,  @germanattanasio says:
>1 version per sdk
>multiple independent versions will make things difficult
>Specially around documentation
>semantic versioning
>x.y.z

I'd like to make this inital release `0.1.0-alpha`. Once we get all of the high priority services and functionality in there we will version up to `1.0.0` and move up from there. What do you think?

How does that sound?

**Comment by mediumTaj** [comment]
@atilatosta so is this PR ok? We will just keep one version for the SDK and version all packages up when whenever we do a release.

**Comment by atilatosta** [comment]
@mediumTaj Ok! All right!

**Pull request merged**
